apiVersion: edgeflare.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/managed-by: edge
  name: example
spec:
  database:
    postgres:
      release:
        chartURL: registry-1.docker.io/bitnamicharts/postgresql:16.4.9
        valuesContent: |
          architecture: replication
          backup:
            enabled: true
          extraEnvVars:
          - name: POSTGRESQL_WAL_LEVEL
            value: logical
          global:
            postgresql:
              # auth:
              #   existingSecret: example-postgresql # must exist if supplied. generated if not
              database: main
          image:
            registry: docker.io
            repository: bitnami/postgresql
            tag: 17.4.0
          persistence:
            enabled: true
            size: 8Gi
          readReplicas:
            extraEnvVars:
            - name: POSTGRESQL_WAL_LEVEL
              value: logical
            persistence:
              enabled: true
              size: 8Gi
            replicaCount: 1
          tls:
            autoGenerated: true
            enabled: true

  auth:
    zitadel:
      release:
        chartURL: registry-1.docker.io/edgeflare/zitadel:8.12.0
        valuesContent: |
          env:
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: PGPASSWORD
                name: example-pguser-postgres
          - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: PGPASSWORD
                name: example-pguser-zitadel
          - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
                name: example-zitadel-firstinstance
          - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
            value: iam@example.local
          image:
            repository: ghcr.io/zitadel/zitadel
            tag: v2.70.0
          replicaCount: 3
          zitadel:
            configmapConfig:
              Database:
                Postgres:
                  Admin:
                    SSL:
                      Mode: require
                    Username: postgres
                  Database: main
                  Host: example-postgres-postgresql-primary
                  Port: 5432
                  User:
                    SSL:
                      Mode: require
                    Username: zitadel
              ExternalDomain: iam.example.local
              ExternalPort: 443
              ExternalSecure: true
              FirstInstance:
                Org:
                  Machine:
                    Machine:
                      Name: Admin
                      Username: zitadel-admin-sa
                    MachineKey:
                      Type: 1
              Machine:
                Identification:
                  Hostname:
                    Enabled: true
                  Webhook:
                    Enabled: false
              TLS:
                Enabled: false
            # masterkeySecretName: example-zitadel-masterkey # must exist if supplied. generated if not
---
