# This rule is not used by the project edge itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over helm.edgeflare.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edge
    app.kubernetes.io/managed-by: kustomize
  name: helm-release-admin-role
rules:
- apiGroups:
  - helm.edgeflare.io
  resources:
  - releases
  verbs:
  - '*'
- apiGroups:
  - helm.edgeflare.io
  resources:
  - releases/status
  verbs:
  - get
