# This rule is not used by the project edge itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to helm.edgeflare.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edge
    app.kubernetes.io/managed-by: kustomize
  name: helm-release-viewer-role
rules:
- apiGroups:
  - helm.edgeflare.io
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.edgeflare.io
  resources:
  - releases/status
  verbs:
  - get
