apiVersion: v1
stringData:
  masterkey: MasterkeyNeedsToHave32Characters
kind: Secret
metadata:
  name: example-zitadel-masterkey
type: Opaque
---
apiVersion: v1
stringData:
  ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: Z!tade1Adm!nPW # aah zitadel errors with easy-to-guess-pw
kind: Secret
metadata:
  name: example-zitadel-firstinstance
type: Opaque
---
apiVersion: v1
stringData:
  PGDATABASE: main
  PGHOST: example-postgres-postgresql-primary.default.svc.cluster.local
  PGPASSWORD: zitadelpw
  PGPORT: "5432"
  PGSSLMODE: require
  PGUSER: zitadel
  conn-string: "host=example-postgres-postgresql-primary.default.svc.cluster.local port=5432 user=postgres password=zitadelpw dbname=main sslmode=require"
kind: Secret
metadata:
  name: example-pguser-zitadel
type: Opaque
---
apiVersion: v1
stringData:
  PGDATABASE: main
  PGHOST: example-postgres-postgresql-primary.default.svc.cluster.local
  PGPASSWORD: postgrespw
  PGPORT: "5432"
  PGSSLMODE: require
  PGUSER: postgres
  conn-string: "host=example-postgres-postgresql-primary.default.svc.cluster.local port=5432 user=postgres password=postgrespw dbname=main sslmode=require"
kind: Secret
metadata:
  name: example-pguser-postgres
type: Opaque
---
apiVersion: v1
stringData:
  postgres-password: postgrespw
  replication-password: replpw
kind: Secret
metadata:
  name: example-postgresql
type: Opaque
---
apiVersion: v1
stringData:
  PGDATABASE: main
  PGHOST: example-postgres-postgresql-primary.default.svc.cluster.local
  PGPASSWORD: postgrestpw
  PGPORT: "5432"
  PGSSLMODE: require
  PGUSER: postgrest
  conn-string: "host=example-postgres-postgresql-primary.default.svc.cluster.local port=5432 user=postgrest password=postgrestpw dbname=main sslmode=require"
kind: Secret
metadata:
  name: example-pguser-postgrest
type: Opaque
---
