rest:
  listenAddr: ":8080"
  pg:
    connString: "host=db-app port=5432 user=pgo password=pgopw dbname=main sslmode=prefer" # container
    # connString: "host=localhost port=5432 user=pgo password=pgopw dbname=main sslmode=prefer"
  oidc:
    issuer: http://iam.192-168-0-10.sslip.io
    clientID: 311437373110026381
    clientSecret: QkqE8W6FUKiQqXCr2Aa2RzzaepkbR0yVdU8WBbaj8LFeGyzz1gtjMb5hvUJnrWmd
    roleClaimKey: .policy.pgrole
  basicAuth: {}
  anonRole: anon

pipeline:
  peers:
  - name: db-auth
    connector: postgres
    config:
      connString: "host=db-auth port=5432 user=postgres password=postgrespw dbname=main sslmode=prefer replication=database"
      replication:
        tables: ["projections.users14"]
  - name: db-app
    connector: postgres
    config:
      connString: "host=db-app port=5432 user=postgres password=postgrespw dbname=main sslmode=prefer"
  - name: debug # logs CDC events to stdout
    connector: debug
  pipelines:
  - name: sync-users-from-db-auth-to-db-app
    sources:
    - name: db-auth
    sinks:
    - name: debug
    - name: db-app
      transformations:
      - type: filter
        config:
          operations: ["c"] # c=create/insert, u=update, d=delete, r=read/select
      - type: extract
        config:
          fields: ["id"]
      - type: replace
        config:
          schemas:
            projections: iam
          tables:
            users14: users
