rest:
  listenAddr: ":8080"
  pg:
    connString: "host=app-db port=5432 user=pgo password=pgopw dbname=main sslmode=prefer" # container
    # connString: "host=localhost port=5432 user=pgo password=pgopw dbname=main sslmode=prefer"
  oidc:
    issuer: http://iam.192-168-0-121.sslip.io
    clientID: 311065325191888901
    clientSecret: WCHwhcHqOFj1igPCh8MvTdidnKMUcUiJV40fnuekKNmY3tdyS6CtIWfRrBjbG24w
    roleClaimKey: .policy.pgrole
  basicAuth: {}
  anonRole: anon

pipeline:
  peers:
  - name: auth-db
    connector: postgres
    config:
      connString: "host=auth-db port=5432 user=postgres password=postgrespw dbname=main sslmode=prefer replication=database"
      replication:
        tables: ["projections.users14"]
  - name: app-db
    connector: postgres
    config:
      connString: "host=app-db port=5432 user=postgres password=postgrespw dbname=main sslmode=prefer"
  - name: debug # logs CDC events to stdout
    connector: debug
  pipelines:
  - name: sync-users-from-auth-db-to-app-db
    sources:
    - name: auth-db
    sinks:
    - name: debug
    - name: app-db
      transformations:
      - type: filter
        config:
          operations: ["c"] # c=create/insert, u=update, d=delete, r=read/select
      - type: extract
        config:
          fields: ["id"]
      - type: replace
        config:
          schemas:
            projections: iam
          tables:
            users14: users
