FROM docker.io/golang:1.24 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

COPY ./go.mod go.mod
COPY ./go.sum go.sum
RUN go mod download

COPY ./internal/util/envoy internal/util/envoy

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o envoy-controlplane ./internal/util/envoy

# runtime image
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/envoy-controlplane .
USER 65532:65532

ENTRYPOINT ["/envoy-controlplane"]
