extraHelmRepos:
- name: couchdb
  url: https://apache.github.io/couchdb-helm
- name: cells
  url: https://download.pydio.com/pub/charts/helm
http:
  auth:
    type: none
  cors:
    enabled: false
    allowOrigins:
    - "*"
  enableLog: true
  port: 8081
kubeconfig: /home/demouser/.kube/127.0.0.1.config
