package common

// DefaultChartURL returns the default chart URL for a given component type
func DefaultChartURL(componentType string) string {
	switch componentType {
	case "postgres":
		return "registry-1.docker.io/bitnamicharts/postgresql:16.4.9"
	case "zitadel":
		return "registry-1.docker.io/edgeflare/zitadel:8.12.0"
	case "keycloak":
		return "registry-1.docker.io/bitnamicharts/keycloak:15.1.0"
	case "postgrest":
		return "registry-1.docker.io/postgrest/postgrest:11.2.0"
	case "seaweedfs":
		return "registry-1.docker.io/chrislusf/seaweedfs:3.52"
	case "minio":
		return "registry-1.docker.io/bitnamicharts/minio:12.6.0"
	case "pgo":
		return "ghcr.io/edgeflare/pgo:0.0.1-alpha1"
	default:
		return ""
	}
}

// DefaultValuesContent returns the default values content for a given component type
func DefaultValuesContent(componentType, projectName string) string {
	switch componentType {
	case "postgres":
		return `
architecture: replication
backup:
  enabled: true
extraEnvVars:
- name: POSTGRESQL_WAL_LEVEL
  value: logical
image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 17.4.0
global:
  postgresql:
    auth:
      existingSecret: ` + projectName + `-postgresql
      database: main
persistence:
  enabled: true
  size: 8Gi
readReplicas:
  extraEnvVars:
  - name: POSTGRESQL_WAL_LEVEL
    value: logical
  persistence:
    enabled: true
    size: 8Gi
  replicaCount: 1
tls:
  autoGenerated: true
  enabled: true
`
	// Add default values for other component types
	default:
		return ""
	}
}
