apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example.local
  namespace: envoy-gateway-system
spec:
  commonName: example.local
  dnsNames:
  - '*.example.local'
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 2160h0m0s
  secretName: example.local-tls
  usages:
  - server auth
  - client auth
  - crl sign
  - digital signature
  - key encipherment
  - cert sign
---
