name: CI

on:
  push:
    branches: [ main, master, dev ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-e2e-build:
    name: lint-test-e2e-build
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
  
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --timeout=10m

      - name: Run Tests
        run: |
          go mod tidy
          make test

      - name: Install kind for E2E Tests
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Run Test e2e
        run: |
          go mod tidy
          make test-e2e

      - name: Build
        run: go build -v -o bin/edge ./cmd/main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: edge-binary
          path: bin/edge
          retention-days: 5
